---

qi_git_repository: https://github.com/avtar/qi-config.git 

qi_ops_email: agill@ocadu.ca

qi_config_temp_dir: ./tmp

qi_jenkins_jobs_dir: ./jenkins_jobs

# FQDN of the host used for hosting Linux VMs.
qi_linux_build_node: h-0007.tor1.inclusivedesign.ca

# The directory in the VM used to mount the file share where all job related commands should be run.
qi_linux_vm_job_commands_directory: /home/vagrant/sync

qi_vagrantfile_url: https://raw.githubusercontent.com/avtar/qi-config/master/files/Vagrantfile.linux
