---

# Read GitHub URL and branch name

# Download .qi.yml from the repository

# Create a JJB defintion
## Download Vagrantfile
## Detect the presence of code coverage report and use publisher if report is available 

# Upload definitions

# Trigger jobs http://stackoverflow.com/questions/20359810/how-to-trigger-jenkins-builds-remotely-and-to-pass-parameters

# gpii-binder command:
# vagrant ssh -c 'cd /home/vagrant/sync && DISPLAY=:0 npm test'

# - name: Create directory for storing downloaded QI configuration files
#   file:
#     path: "{{ qi_config_temp_dir }}"
#     state: directory
#     mode: 0755

# - name: Download QI configs
#   get_url:
#     url: "{{ item.value.url }}"
#     dest: "{{ qi_config_temp_dir }}/{{ item.key }}.yml"
#   with_dict: "{{ qi_configs }}"


- debug: var: "{{ env_runtime }}"