---
- hosts: localhost
  user: deploy

  vars_files:
    - vars/main.yml

  tasks:
    - name: Generate JJB definition defaults
      template:
        src: defaults.yml.j2
        dest: "{{ qi_jenkins_jobs_dir }}/defaults.yml"
        mode: 0644

    - name: Generate JJB definition used by Jenkins server
      template:
        src: update-jjb-definitions.yml.j2
        dest: "{{ qi_jenkins_jobs_dir }}/update-jjb-definitions.yml"
        mode: 0644
    
    - name: Generate JJB definition for {{ apps.0.app_name }}
      template:
        src: linux-jjb-definition.yml.j2
        dest: "{{ qi_jenkins_jobs_dir }}/{{ apps.0.app_name }}.yml"
        mode: 0644
